Java 8 and 9 build pack pre-hook script updates (verified working).
- Fixed duplicate output lines issue (was due to improper stdout+stderr
  redirect exec).
- Also updated nodes.js, play-framework, and scala-sbt build-pack pre-hook
  scripts.

diff --git a/build-packs/java8-mvn/pre-hook b/build-packs/java8-mvn/pre-hook
--- a/build-packs/java8-mvn/pre-hook
+++ b/build-packs/java8-mvn/pre-hook
@@ -1,15 +1,24 @@
 #!/bin/bash
 
+set -o nounset
+
+logfile=/app/out
+exec > "${logfile}" 2>&1
+
 ##
-# Python dependencies hook.
+# Java 8 app dependencies and build hook.
 #
 
 function abortIfNonZero() {
     # @param $1 command return code/exit status (e.g. $?, '0', '1').
     # @param $2 error message if exit status was non-zero.
-    local rc=$1
-    local what=$2
-    test $rc -ne 0 && echo "error: ${what} exited with non-zero status ${rc}" >> /app/out && exit $rc || :
+    local rc=${1:-}
+    local what=${2:-}
+    if [ ${rc} -ne 0 ] ; then
+        echo "error: ${what} exited with non-zero status ${rc}"
+        echo "RETURN_CODE: ${rc}"
+        exit ${rc}
+    fi
 }
 
 cd /app/src
@@ -17,12 +26,13 @@ abortIfNonZero $? 'Changing directory to "/app/src"'
 
 dependenciesPath='/app/.shipbuilder/.m2/repository'
 
-test ! -d "${dependenciesPath}" && mkdir -p "${dependenciesPath}"
+mkdir -p "${dependenciesPath}"
+abortIfNonZero $? 'Creating directory dependenciesPath=${dependenciesPath}'
 
 # Support sbt-assembly deployments, @see https://github.com/sbt/sbt-assembly for more information.
-stdbuf -o0 mvn clean install -DskipTests 2>&1 >> /app/out
+stdbuf -o0 mvn clean install -DskipTests 2>&1
 rc=$?
-abortIfNonZero $rc '`mvn clean install` failed'
+abortIfNonZero ${rc} "Command 'mvn clean install -DskipTests'"
 
-echo "RETURN_CODE: ${rc}" >> /app/out
-exit $rc
+echo "RETURN_CODE: ${rc}"
+exit ${rc}
diff --git a/build-packs/nodejs/pre-hook b/build-packs/nodejs/pre-hook
--- a/build-packs/nodejs/pre-hook
+++ b/build-packs/nodejs/pre-hook
@@ -1,23 +1,36 @@
 #!/bin/bash
 
-logfile=/app/out
-exec >> "${logfile}" 2>&1
-
-set -x
-
 set -o errexit
 set -o pipefail
 set -o nounset
 
+logfile=/app/out
+exec > "${logfile}" 2>&1
+
+set -x
+
 ##
-# Node.js dependencies hook.
+# Node.js app dependencies and build hook.
 #
+
+function abortIfNonZero() {
+    # @param $1 command return code/exit status (e.g. $?, '0', '1').
+    # @param $2 error message if exit status was non-zero.
+    local rc=${1:-}
+    local what=${2:-}
+    if [ ${rc} -ne 0 ] ; then
+        echo "error: ${what} exited with non-zero status ${rc}"
+        echo "RETURN_CODE: ${rc}"
+        exit ${rc}
+    fi
+}
 
 cd /app/src
 
 dependenciesPath=/app/.shipbuilder
 
 mkdir -p "${dependenciesPath}"
+abortIfNonZero $? 'Creating directory dependenciesPath=${dependenciesPath}'
 
 if [ -r 'package.json' ] ; then
     if [ -L 'node_modules' ] ; then
@@ -32,11 +45,13 @@ if [ -r 'package.json' ] ; then
 
     echo '--> Installing npm dependencies'
     stdbuf -o0 npm install 2>&1
+    abortIfNonZero $? "Command 'stdbuf -o0 npm install"
 
     ln -s "${dependenciesPath}/node_modules" /app/src/node_modules
+    abortIfNonZero $? "Command 'ln -s ${dependenciesPath}/node_modules /app/src/node_modules'"
 
 else
-    echo 'warning: no "packages.json" file found'
+    echo 'Warning: no "packages.json" file found'
 fi
 
 echo "RETURN_CODE: 0"
diff --git a/build-packs/playframework2/pre-hook b/build-packs/playframework2/pre-hook
--- a/build-packs/playframework2/pre-hook
+++ b/build-packs/playframework2/pre-hook
@@ -1,7 +1,35 @@
 #!/bin/bash
+
+set -o nounset
+
+logfile=/app/out
+exec > "${logfile}" 2>&1
+
+##
+# Play framework app dependencies build hook.
+#
+
+function abortIfNonZero() {
+    # @param $1 command return code/exit status (e.g. $?, '0', '1').
+    # @param $2 error message if exit status was non-zero.
+    local rc=${1:-}
+    local what=${2:-}
+    if [ ${rc} -ne 0 ] ; then
+        echo "error: ${what} exited with non-zero status ${rc}"
+        echo "RETURN_CODE: ${rc}"
+        exit ${rc}
+    fi
+}
+
 cd /app/src
+abortIfNonZero $? 'Changing directory to "/app/src"'
+
 export _JAVA_OPTIONS='-Xmx5000m -XX:-UseConcMarkSweepGC'
-stdbuf -o0 play compile >> /app/out
+
+stdbuf -o0 play compile 2>&1
 rc=$?
-echo "RETURN_CODE: ${rc}" >> /app/out
-exit $rc
+abortIfNonZero ${rc} "Command 'stdbuf -o0 play compile'"
+
+echo "RETURN_CODE: ${rc}"
+
+exit ${rc}
